In [1]:
import numpy as np
import pandas as pd

In [2]:
#RAW DATA FROM SCRAPPIN
df= pd.read_csv('/home/gibeon/Desktop/MY/fvldata/STORAGE/TABLES/pTable001.csv')

#df['Pos'] = df.index
#df.reset_index(level=0, inplace=True)

#df['INDX'] = pd.Series(list(range(len(df['Team']))))
df.head()    ####  REMOVE DIFF,one of WDL,

Pos  Dir           Team   P  W  D  L  GF  GA  DIFF  Points        Season
0    1   -1      VL Moscow  12  8  1  3  21   9    12      25  Season 12657
1    2    1        VL Rome  12  7  2  3  22  16     6      23  Season 12657
2    3    0      VL London  12  7  2  3  19  17     2      23  Season 12657
3    4   -1  VL Copenhagen  12  6  3  3  11  10     1      21  Season 12657
4    5    0      VL Madrid  12  5  5  2  23  13    10      20  Season 12657

In [3]:
# df2 = df.set_index(['P', 'Pos'],drop=False)  ##interesing stuff
# df2.head()


In [4]:
#df.head()
df['Team'].unique()

array(['VL Moscow', 'VL Rome', 'VL London', 'VL Copenhagen', 'VL Madrid',
       'VL Berlin', 'VL Kiev', 'VL Amsterdam', 'VL Bern', 'VL Vienna',
       'VL Lisbon', 'VL Athens', 'VL Paris', 'VL Zagreb', 'VL Prague',
       'VL Ankara'], dtype=object)

In [5]:
def teamCoded(S):
    
#     cats=['MADRID', 'AMSTERDAM','BERLIN','LONDON','ROME','OSLO','LISBON','PARIS','BRUSSELS','ATHENS','STOCKHOLM',
#           'COPENHAGEN','VIENNA', 'ANKARA','EDINBURGH','BERN']
    
    cats=['MADRID', 'AMSTERDAM','BERLIN','LONDON','ROME','MOSCOW','LISBON','PARIS','ZAGREB','ATHENS','PRAGUE',
          'COPENHAGEN','VIENNA', 'ANKARA','KIEV','BERN']

    catsRev=[]
    for tm in S:
        if tm == cats[0]:
            catsRev.append(1)
        elif tm == cats[1]:
            catsRev.append(2)
        elif tm == cats[2]:
            catsRev.append(3)
        elif tm == cats[3]:
            catsRev.append(4)
        elif tm == cats[4]:
            catsRev.append(5)
        elif tm == cats[5]:
            catsRev.append(6)
        elif tm == cats[6]:
            catsRev.append(7)
        elif tm == cats[7]:
            catsRev.append(8)
        elif tm == cats[8]:
            catsRev.append(9)
        elif tm == cats[9]:
            catsRev.append(10)
        elif tm == cats[10]:
            catsRev.append(11)
        elif tm == cats[11]:
            catsRev.append(12)
        elif tm == cats[12]:
            catsRev.append(13)
        elif tm == cats[13]:
            catsRev.append(14)
        elif tm == cats[14]:
            catsRev.append(15)
        elif tm == cats[15]:
            catsRev.append(16)
    return catsRev


df['TEAM']=pd.Series([x.split()[1].upper() for x in df.Team])
df['HOMECODE']=teamCoded(df['TEAM'])
df['AWAYCODE']=teamCoded(df['TEAM'])

In [6]:
df.head()

Pos  Dir           Team   P  W  D  L  GF  GA  DIFF  Points        Season  \
0    1   -1      VL Moscow  12  8  1  3  21   9    12      25  Season 12657   
1    2    1        VL Rome  12  7  2  3  22  16     6      23  Season 12657   
2    3    0      VL London  12  7  2  3  19  17     2      23  Season 12657   
3    4   -1  VL Copenhagen  12  6  3  3  11  10     1      21  Season 12657   
4    5    0      VL Madrid  12  5  5  2  23  13    10      20  Season 12657   

         TEAM  HOMECODE  AWAYCODE  
0      MOSCOW         6         6  
1        ROME         5         5  
2      LONDON         4         4  
3  COPENHAGEN        12        12  
4      MADRID         1         1

In [7]:
df1 = df[df.isna().any(axis=1)]

In [8]:
df1

Empty DataFrame
Columns: [Pos, Dir, Team, P, W, D, L, GF, GA, DIFF, Points, Season, TEAM, HOMECODE, AWAYCODE]
Index: []

In [9]:
dfR= pd.read_csv('/home/gibeon/Desktop/MY/fvldata/STORAGE/TABLES/pResu001.csv')

#dfR= pd.read_csv('/home/ideon/Desktop/DATA CENTRE/resultDataR.csv')
dfR.head()

TIMER                       TEAMSr  HTR  FTR  P        Season
0  17/07/19 08:10      VL Berlin  -  VL Athens  2:0  4:0  1  Season 12657
1  17/07/19 08:10       VL Zagreb  -  VL Paris  1:3  1:3  1  Season 12657
2  17/07/19 08:10  VL Copenhagen  -  VL Moscow  0:0  1:0  1  Season 12657
3  17/07/19 08:10        VL London  -  VL Rome  0:0  2:0  1  Season 12657
4  17/07/19 08:10          VL Bern  -  VL Kiev  2:0  4:0  1  Season 12657

In [10]:


#function to input(ps) DF column of form/content (3:2) eg HT result or HT results and out put ps.series with eithe 0,1 or 2
def results(ps):

    #ps = ps.dropna()
    lp=[]
    for x in ps:
       # print(x)
        
        h=x.replace(':','  ')[:1]
      #  print(h)
        a=x.replace(':','  ')[1:]
        if float(h) > float(a):
            lp.append(1)

        elif float(a) > float(h):
            lp.append(2)
        else:
            lp.append(0)

    return pd.Series(lp)



def over_under(ps,n):
    lp=[]
    for x in ps:
        h=x.replace(':','  ')[:1]
        a=x.replace(':','  ')[1:]
        # if goals sum is greater than n value is 1
        
        if (float(h) + float(a)) > float(n):
            lp.append(1)

        else:
            #means it is under n eg under 2.5
            lp.append(0)

    return pd.Series(lp)

##addition collumn of all goals
def goalsum(ps):
    lp=[]
    for x in ps:
        h=x.replace(':','  ')[:1]
        a=x.replace(':','  ')[1:]
        # if goals sum is greater than n value is 1
        
        lp.append((float(h) + float(a)))

    return pd.Series(lp)

In [11]:
#======================================================================
dfR['TEAMSr']
dfR['TEAMSr']=pd.Series([x.upper() for x in dfR.TEAMSr])
dfR['TEAMSr']=pd.Series([x.upper() for x in dfR.TEAMSr])
#split TEAMS into HOME & AWAY 
dfR['HOME']=pd.Series([x.split()[1] for x in dfR.TEAMSr]) 
dfR['AWAY']=pd.Series([x.split()[4] for x in dfR.TEAMSr])

dfR['TIMEr']=pd.Series([x.split()[1] for x in dfR.TIMER])
#Use teamCode FX to code HOME & AWAY collumns and crean new HOMECODE & AWAYCODE
dfR['TC']=dfR['HOME']+' '+dfR['AWAY']

dfR['HOMECODE']=teamCoded(dfR['HOME'])
dfR['AWAYCODE']=teamCoded(dfR['AWAY'])
#dfR['TEAMSC']=dfR['HOMECODE'] + dfR['AWAYCODE']
#teamCode(dfR['HOME'])


    
dfR['FT_Goals']=pd.Series([str(x).replace(':','  ')[:] for x in dfR.FTR])
dfR['HT_Goals']=pd.Series([str(x).replace(':','  ')[:] for x in dfR.HTR])
dfR['FT_home_goals']=pd.Series([str(x).replace(':','  ')[:1] for x in dfR.FTR])
dfR['FT_away_goals']=pd.Series([str(x).replace(':','  ')[1:] for x in dfR.FTR])
dfR['HT_home_goals']=pd.Series([str(x).replace(':','  ')[:1] for x in dfR.HTR])
dfR['HT_away_goals']=pd.Series([str(x).replace(':','  ')[1:] for x in dfR.HTR])



dfR['FT_Results_1_0_2']=results(dfR['FT_Goals'])
dfR['HT_Results_1_0_2']=results(dfR['HT_Goals'])


# FT UNDER /OVER Goals
p = 3.5
n = 2.5
q = 1.5

dfR['Under_Over_3.5']= over_under(dfR['FT_Goals'],p)
dfR['Under_Over_2.5']= over_under(dfR['FT_Goals'],n)
dfR['Under_Over_1.5']= over_under(dfR['FT_Goals'],q)



dfR['Sum_Goals']= goalsum(dfR['FT_Goals'])





dfR['Sum_Goals']= goalsum(dfR['FT_Goals'])# addition column of all goals

#dfR['HT_Results_1_0_2']=results(dfR['HT_Goals'])

colum=['P','Season','TC','HOMECODE', 'AWAYCODE','TIMEr','HTR', 'FTR', 'HT_home_goals', 'HT_away_goals',
       'FT_home_goals','FT_away_goals','Sum_Goals','HT_Results_1_0_2','FT_Results_1_0_2','Under_Over_1.5','Under_Over_2.5',
       'Under_Over_3.5']
resu= dfR.reindex(columns=colum).fillna(0)#.values


colum=['TC','HOMECODE', 'AWAYCODE','TIMEr','HTR', 'FTR', 'HT_home_goals', 'HT_away_goals',
       'FT_home_goals','FT_away_goals','HT_Results_1_0_2','FT_Results_1_0_2','TIMER','TIMED','1','2','X','HT1','HT2','HTX','FS (0:0)','FS(0:0)2','FS(0:0)X','G(0.5)O','G(0.5)U',
         'G(1.5)O','G(1.5)U','G(2.5)O','G(2.5)U','G(3.5)O','G(3.5)U','G(4.5)O','G(4.5)U','Under_Over_1.5','Under_Over_2.5',
       'Under_Over_3.5']

In [12]:
resu.head()

P        Season                 TC  HOMECODE  AWAYCODE  TIMEr  HTR  FTR  \
0  1  Season 12657      BERLIN ATHENS         3        10  08:10  2:0  4:0   
1  1  Season 12657       ZAGREB PARIS         9         8  08:10  1:3  1:3   
2  1  Season 12657  COPENHAGEN MOSCOW        12         6  08:10  0:0  1:0   
3  1  Season 12657        LONDON ROME         4         5  08:10  0:0  2:0   
4  1  Season 12657          BERN KIEV        16        15  08:10  2:0  4:0   

  HT_home_goals HT_away_goals FT_home_goals FT_away_goals  Sum_Goals  \
0             2             0             4             0        4.0   
1             1             3             1             3        4.0   
2             0             0             1             0        1.0   
3             0             0             2             0        2.0   
4             2             0             4             0        4.0   

   HT_Results_1_0_2  FT_Results_1_0_2  Under_Over_1.5  Under_Over_2.5  \
0                 1                 1               1               1   
1                 2                 2               1               1   
2                 0                 1               0               0   
3                 0                 1               1               0   
4                 1                 1               1               1   

   Under_Over_3.5  
0               1  
1               1  
2               0  
3               0  
4               1

In [13]:
gr = resu.groupby([resu['HOMECODE'], resu['AWAYCODE']])

In [14]:
gr # what the f*ck is this pandas object

In [15]:
df.head()

Pos  Dir           Team   P  W  D  L  GF  GA  DIFF  Points        Season  \
0    1   -1      VL Moscow  12  8  1  3  21   9    12      25  Season 12657   
1    2    1        VL Rome  12  7  2  3  22  16     6      23  Season 12657   
2    3    0      VL London  12  7  2  3  19  17     2      23  Season 12657   
3    4   -1  VL Copenhagen  12  6  3  3  11  10     1      21  Season 12657   
4    5    0      VL Madrid  12  5  5  2  23  13    10      20  Season 12657   

         TEAM  HOMECODE  AWAYCODE  
0      MOSCOW         6         6  
1        ROME         5         5  
2      LONDON         4         4  
3  COPENHAGEN        12        12  
4      MADRID         1         1

In [21]:
##magic happens here

dff1 = pd.merge (df,resu, on =('Season','P','HOMECODE'))#,by='Season')#,left_on='lkey', right_on='rkey')
#dff1['AWAYCODE'] = dff1['AWAYCODE_x']
dff2 = pd.merge(df,resu, on =('Season','P','AWAYCODE'))#,left_on='lkey', right_on='rkey') 

In [49]:
dff1.sort_values(by=['Season','P'])
dff1= dff1.drop_duplicates()
dff1

Pos  Dir           Team   P   W   D   L  GF  GA  DIFF  ...  \
0       4   -1  VL Copenhagen  12   6   3   3  11  10     1  ...   
3       5    0      VL Madrid  12   5   5   2  23  13    10  ...   
6       6   -1      VL Berlin  12   6   2   4  21  11    10  ...   
9       7    1        VL Kiev  12   6   2   4  24  23     1  ...   
12      9    0        VL Bern  12   4   3   5  14  12     2  ...   
15     10   -1      VL Vienna  12   4   2   6  15  16    -1  ...   
18     12    1      VL Athens  12   4   2   6  15  19    -4  ...   
21     14   -1      VL Zagreb  12   3   3   6  12  18    -6  ...   
24      1    0      VL Moscow  13   9   1   3  25  10    15  ...   
27      2    0        VL Rome  13   8   2   3  25  17     8  ...   
30      7   -1   VL Amsterdam  13   5   5   3  17  16     1  ...   
33      9   -1       VL Paris  13   4   3   6  22  20     2  ...   
36     11    0      VL Lisbon  13   3   6   4  14  17    -3  ...   
39     12   -1      VL Prague  13   5   0   8  14  26   -12  ...   
42     14    1      VL Athens  13   4   2   7  15  21    -6  ...   
45     16    0      VL Ankara  13   2   2   9  12  24   -12  ...   
48      2    0        VL Rome   1   1   0   0   4   2     2  ...   
49      3    0      VL Moscow   1   1   0   0   3   1     2  ...   
50      4    0   VL Amsterdam   1   1   0   0   2   0     2  ...   
51      7    0      VL Vienna   1   1   0   0   1   0     1  ...   
52      9    0      VL Prague   1   0   1   0   1   1     0  ...   
53     10    0      VL Athens   1   0   0   1   1   2    -1  ...   
54     12    0      VL Zagreb   1   0   0   1   0   1    -1  ...   
55     16    0        VL Bern   1   0   0   1   0   4    -4  ...   
56      1   -1      VL Berlin   2   2   0   0   5   1     4  ...   
57      3    1      VL London   2   1   1   0   7   3     4  ...   
58      5   -1  VL Copenhagen   2   1   1   0   2   1     1  ...   
59      7   -1      VL Lisbon   2   1   0   1   4   4     0  ...   
60      8   -1      VL Madrid   2   1   0   1   4   5    -1  ...   
61     10    1       VL Paris   2   0   2   0   2   2     0  ...   
...   ...  ...            ...  ..  ..  ..  ..  ..  ..   ...  ...   
6738    4    0   VL Amsterdam  27  15   5   7  47  33    14  ...   
6739    6    1      VL Moscow  27  13   7   7  40  25    15  ...   
6740    9    0      VL Ankara  27  11   2  14  32  40    -8  ...   
6741   10    0      VL London  27  10   4  13  38  38     0  ...   
6742   11    0        VL Bern  27   8   6  13  34  44   -10  ...   
6743   16    1      VL Athens  27   7   3  17  26  52   -26  ...   
6744    1    0      VL Berlin  28  18   3   7  50  28    22  ...   
6745    5    0        VL Rome  28  16   3   9  47  33    14  ...   
6746    8    0      VL Prague  28  11   5  12  38  45    -7  ...   
6747   10    1      VL Ankara  28  11   2  15  33  42    -9  ...   
6748   12   -1       VL Paris  28   7   7  14  34  46   -12  ...   
6749   13   -1        VL Kiev  28   8   3  17  38  54   -16  ...   
6750   15    1      VL Vienna  28   7   5  16  19  38   -19  ...   
6751   16    1  VL Copenhagen  28   7   4  17  19  39   -20  ...   
6752    2    0      VL Madrid  29  16   8   5  60  33    27  ...   
6753    3    0   VL Amsterdam  29  17   5   7  51  33    18  ...   
6754    4    0      VL Lisbon  29  17   5   7  43  25    18  ...   
6755    6   -1      VL Zagreb  29  12  11   6  39  27    12  ...   
6756    7    1      VL Moscow  29  13   7   9  41  29    12  ...   
6757    8   -1      VL London  29  12   4  13  43  38     5  ...   
6758   11    0        VL Bern  29   8   6  15  36  49   -13  ...   
6759   13   -1      VL Athens  29   8   4  17  29  54   -25  ...   
6760    1    0      VL Berlin  30  20   3   7  54  29    25  ...   
6761    5    0        VL Rome  30  17   3  10  52  38    14  ...   
6762   10    0      VL Ankara  30  12   2  16  34  45   -11  ...   
6763   11   -1       VL Paris  30   8   8  14  37  47   -10  ...   
6764   13    0      VL Athens  30   8   5  17  30  55   -25  .

In [50]:
dff1.sort_values(by=['Season','P'])
dff1 = dff1.drop_duplicates()
dff1

Pos  Dir           Team   P   W   D   L  GF  GA  DIFF  ...  \
0       4   -1  VL Copenhagen  12   6   3   3  11  10     1  ...   
3       5    0      VL Madrid  12   5   5   2  23  13    10  ...   
6       6   -1      VL Berlin  12   6   2   4  21  11    10  ...   
9       7    1        VL Kiev  12   6   2   4  24  23     1  ...   
12      9    0        VL Bern  12   4   3   5  14  12     2  ...   
15     10   -1      VL Vienna  12   4   2   6  15  16    -1  ...   
18     12    1      VL Athens  12   4   2   6  15  19    -4  ...   
21     14   -1      VL Zagreb  12   3   3   6  12  18    -6  ...   
24      1    0      VL Moscow  13   9   1   3  25  10    15  ...   
27      2    0        VL Rome  13   8   2   3  25  17     8  ...   
30      7   -1   VL Amsterdam  13   5   5   3  17  16     1  ...   
33      9   -1       VL Paris  13   4   3   6  22  20     2  ...   
36     11    0      VL Lisbon  13   3   6   4  14  17    -3  ...   
39     12   -1      VL Prague  13   5   0   8  14  26   -12  ...   
42     14    1      VL Athens  13   4   2   7  15  21    -6  ...   
45     16    0      VL Ankara  13   2   2   9  12  24   -12  ...   
48      2    0        VL Rome   1   1   0   0   4   2     2  ...   
49      3    0      VL Moscow   1   1   0   0   3   1     2  ...   
50      4    0   VL Amsterdam   1   1   0   0   2   0     2  ...   
51      7    0      VL Vienna   1   1   0   0   1   0     1  ...   
52      9    0      VL Prague   1   0   1   0   1   1     0  ...   
53     10    0      VL Athens   1   0   0   1   1   2    -1  ...   
54     12    0      VL Zagreb   1   0   0   1   0   1    -1  ...   
55     16    0        VL Bern   1   0   0   1   0   4    -4  ...   
56      1   -1      VL Berlin   2   2   0   0   5   1     4  ...   
57      3    1      VL London   2   1   1   0   7   3     4  ...   
58      5   -1  VL Copenhagen   2   1   1   0   2   1     1  ...   
59      7   -1      VL Lisbon   2   1   0   1   4   4     0  ...   
60      8   -1      VL Madrid   2   1   0   1   4   5    -1  ...   
61     10    1       VL Paris   2   0   2   0   2   2     0  ...   
...   ...  ...            ...  ..  ..  ..  ..  ..  ..   ...  ...   
6738    4    0   VL Amsterdam  27  15   5   7  47  33    14  ...   
6739    6    1      VL Moscow  27  13   7   7  40  25    15  ...   
6740    9    0      VL Ankara  27  11   2  14  32  40    -8  ...   
6741   10    0      VL London  27  10   4  13  38  38     0  ...   
6742   11    0        VL Bern  27   8   6  13  34  44   -10  ...   
6743   16    1      VL Athens  27   7   3  17  26  52   -26  ...   
6744    1    0      VL Berlin  28  18   3   7  50  28    22  ...   
6745    5    0        VL Rome  28  16   3   9  47  33    14  ...   
6746    8    0      VL Prague  28  11   5  12  38  45    -7  ...   
6747   10    1      VL Ankara  28  11   2  15  33  42    -9  ...   
6748   12   -1       VL Paris  28   7   7  14  34  46   -12  ...   
6749   13   -1        VL Kiev  28   8   3  17  38  54   -16  ...   
6750   15    1      VL Vienna  28   7   5  16  19  38   -19  ...   
6751   16    1  VL Copenhagen  28   7   4  17  19  39   -20  ...   
6752    2    0      VL Madrid  29  16   8   5  60  33    27  ...   
6753    3    0   VL Amsterdam  29  17   5   7  51  33    18  ...   
6754    4    0      VL Lisbon  29  17   5   7  43  25    18  ...   
6755    6   -1      VL Zagreb  29  12  11   6  39  27    12  ...   
6756    7    1      VL Moscow  29  13   7   9  41  29    12  ...   
6757    8   -1      VL London  29  12   4  13  43  38     5  ...   
6758   11    0        VL Bern  29   8   6  15  36  49   -13  ...   
6759   13   -1      VL Athens  29   8   4  17  29  54   -25  ...   
6760    1    0      VL Berlin  30  20   3   7  54  29    25  ...   
6761    5    0        VL Rome  30  17   3  10  52  38    14  ...   
6762   10    0      VL Ankara  30  12   2  16  34  45   -11  ...   
6763   11   -1       VL Paris  30   8   8  14  37  47   -10  ...   
6764   13    0      VL Athens  30   8   5  17  30  55   -25  .

In [51]:
#dff1.iloc[:, 1:82]#[dff1.TEAM == 'MADRID']  #  most IMPORTANT FILTER OF DFS....NOTE NOTE NOTE
#len(dff1.columns)#[data.three > 5]
#len(dff1.columns)

dff1.iloc[:, 1:20]#[dff1.TEAM == 'MADRID']

Dir           Team   P   W   D   L  GF  GA  DIFF  Points        Season  \
0      -1  VL Copenhagen  12   6   3   3  11  10     1      21  Season 12657   
3       0      VL Madrid  12   5   5   2  23  13    10      20  Season 12657   
6      -1      VL Berlin  12   6   2   4  21  11    10      20  Season 12657   
9       1        VL Kiev  12   6   2   4  24  23     1      20  Season 12657   
12      0        VL Bern  12   4   3   5  14  12     2      15  Season 12657   
15     -1      VL Vienna  12   4   2   6  15  16    -1      14  Season 12657   
18      1      VL Athens  12   4   2   6  15  19    -4      14  Season 12657   
21     -1      VL Zagreb  12   3   3   6  12  18    -6      12  Season 12657   
24      0      VL Moscow  13   9   1   3  25  10    15      28  Season 12657   
27      0        VL Rome  13   8   2   3  25  17     8      26  Season 12657   
30     -1   VL Amsterdam  13   5   5   3  17  16     1      20  Season 12657   
33     -1       VL Paris  13   4   3   6  22  20     2      15  Season 12657   
36      0      VL Lisbon  13   3   6   4  14  17    -3      15  Season 12657   
39     -1      VL Prague  13   5   0   8  14  26   -12      15  Season 12657   
42      1      VL Athens  13   4   2   7  15  21    -6      14  Season 12657   
45      0      VL Ankara  13   2   2   9  12  24   -12       8  Season 12657   
48      0        VL Rome   1   1   0   0   4   2     2       3  Season 12656   
49      0      VL Moscow   1   1   0   0   3   1     2       3  Season 12656   
50      0   VL Amsterdam   1   1   0   0   2   0     2       3  Season 12656   
51      0      VL Vienna   1   1   0   0   1   0     1       3  Season 12656   
52      0      VL Prague   1   0   1   0   1   1     0       1  Season 12656   
53      0      VL Athens   1   0   0   1   1   2    -1       0  Season 12656   
54      0      VL Zagreb   1   0   0   1   0   1    -1       0  Season 12656   
55      0        VL Bern   1   0   0   1   0   4    -4       0  Season 12656   
56     -1      VL Berlin   2   2   0   0   5   1     4       6  Season 12656   
57      1      VL London   2   1   1   0   7   3     4       4  Season 12656   
58     -1  VL Copenhagen   2   1   1   0   2   1     1       4  Season 12656   
59     -1      VL Lisbon   2   1   0   1   4   4     0       3  Season 12656   
60     -1      VL Madrid   2   1   0   1   4   5    -1       3  Season 12656   
61      1       VL Paris   2   0   2   0   2   2     0       2  Season 12656   
...   ...            ...  ..  ..  ..  ..  ..  ..   ...     ...           ...   
6738    0   VL Amsterdam  27  15   5   7  47  33    14      50  Season 12628   
6739    1      VL Moscow  27  13   7   7  40  25    15      46  Season 12628   
6740    0      VL Ankara  27  11   2  14  32  40    -8      35  Season 12628   
6741    0      VL London  27  10   4  13  38  38     0      34  Season 12628   
6742    0        VL Bern  27   8   6  13  34  44   -10      30  Season 12628   
6743    1      VL Athens  27   7   3  17  26  52   -26      24  Season 12628   
6744    0      VL Berlin  28  18   3   7  50  28    22      57  Season 12628   
6745    0        VL Rome  28  16   3   9  47  33    14      51  Season 12628   
6746    0      VL Prague  28  11   5  12  38  45    -7      38  Season 12628   
6747    1      VL Ankara  28  11   2  15  33  42    -9      35  Season 12628   
6748   -1       VL Paris  28   7   7  14  34  46   -12      28  Season 12628   
6749   -1        VL Kiev  28   8   3  17  38  54   -16      27  Season 12628   
6750    1      VL Vienna  28   7   5  16  19  38   -19      26  Season 12628   
6751    1  VL Copenhagen  28   7   4  17  19  39   -20      25  Season 12628   
6752    0      VL Madrid  29  16   8   5  60  33    27      56  Season 12628   
6753    0   VL Amsterdam  29  17   5   7  51  33    18      56  Season 12628   
6754    0      VL Lisbon  29  17   5   7  43  25    18      56  Season 12628   
6755   -1      VL Zagreb  29  12  11   6  39  27    12      47  Season 12628   
6756  

In [52]:
#dff2.iloc[:, 31:52]#[data.three > 5]
#len(dff1.columns)
dff2['HOMECODE'] = dff2['HOMECODE_y']
#dff2.iloc[:, 1:82]#[dff2.TEAM == 'VIENNA']

In [53]:
datag = pd.merge(dff1,dff2, on =('Season','P','HOMECODE'))

In [54]:
datag.sort_values(by=['Season','P'])
datag = datag.drop_duplicates()
datag

Pos_x  Dir_x         Team_x   P  W_x  D_x  L_x  GF_x  GA_x  DIFF_x  ...  \
0         4     -1  VL Copenhagen  12    6    3    3    11    10       1  ...   
3         5      0      VL Madrid  12    5    5    2    23    13      10  ...   
6         6     -1      VL Berlin  12    6    2    4    21    11      10  ...   
9         7      1        VL Kiev  12    6    2    4    24    23       1  ...   
12        9      0        VL Bern  12    4    3    5    14    12       2  ...   
15       10     -1      VL Vienna  12    4    2    6    15    16      -1  ...   
18       12      1      VL Athens  12    4    2    6    15    19      -4  ...   
21       14     -1      VL Zagreb  12    3    3    6    12    18      -6  ...   
24        1      0      VL Moscow  13    9    1    3    25    10      15  ...   
27        2      0        VL Rome  13    8    2    3    25    17       8  ...   
30        7     -1   VL Amsterdam  13    5    5    3    17    16       1  ...   
33        9     -1       VL Paris  13    4    3    6    22    20       2  ...   
36       11      0      VL Lisbon  13    3    6    4    14    17      -3  ...   
39       12     -1      VL Prague  13    5    0    8    14    26     -12  ...   
42       14      1      VL Athens  13    4    2    7    15    21      -6  ...   
45       16      0      VL Ankara  13    2    2    9    12    24     -12  ...   
48        2      0        VL Rome   1    1    0    0     4     2       2  ...   
49        3      0      VL Moscow   1    1    0    0     3     1       2  ...   
50        4      0   VL Amsterdam   1    1    0    0     2     0       2  ...   
51        7      0      VL Vienna   1    1    0    0     1     0       1  ...   
52        9      0      VL Prague   1    0    1    0     1     1       0  ...   
53       10      0      VL Athens   1    0    0    1     1     2      -1  ...   
54       12      0      VL Zagreb   1    0    0    1     0     1      -1  ...   
55       16      0        VL Bern   1    0    0    1     0     4      -4  ...   
56        1     -1      VL Berlin   2    2    0    0     5     1       4  ...   
57        3      1      VL London   2    1    1    0     7     3       4  ...   
58        5     -1  VL Copenhagen   2    1    1    0     2     1       1  ...   
59        7     -1      VL Lisbon   2    1    0    1     4     4       0  ...   
60        8     -1      VL Madrid   2    1    0    1     4     5      -1  ...   
61       10      1       VL Paris   2    0    2    0     2     2       0  ...   
...     ...    ...            ...  ..  ...  ...  ...   ...   ...     ...  ...   
6738      4      0   VL Amsterdam  27   15    5    7    47    33      14  ...   
6739      6      1      VL Moscow  27   13    7    7    40    25      15  ...   
6740      9      0      VL Ankara  27   11    2   14    32    40      -8  ...   
6741     10      0      VL London  27   10    4   13    38    38       0  ...   
6742     11      0        VL Bern  27    8    6   13    34    44     -10  ...   
6743     16      1      VL Athens  27    7    3   17    26    52     -26  ...   
6744      1      0      VL Berlin  28   18    3    7    50    28      22  ...   
6745      5      0        VL Rome  28   16    3    9    47    33      14  ...   
6746      8      0      VL Prague  28   11    5   12    38    45      -7  ...   
6747     10      1      VL Ankara  28   11    2   15    33    42      -9  ...   
6748     12     -1       VL Paris  28    7    7   14    34    46     -12  ...   
6749     13     -1        VL Kiev  28    8    3   17    38    54     -16  ...   
6750     15      1      VL Vienna  28    7    5   16    19    38     -19  ...   
6751     16      1  VL Copenhagen  28    7    4   17    19    39     -20  ...   
6752      2      0      VL Madrid  29   16    8    5    60    33      27  ...   
6753      3      0   VL Amsterdam  29   17    5    7    51    33      18  ...   
6754      4      0      VL Lisbon  29   17    5    7    43    25      18  ...   
6755      6     -1      VL Zagreb  29

In [55]:
datag.head()

Pos_x  Dir_x         Team_x   P  W_x  D_x  L_x  GF_x  GA_x  DIFF_x  ...  \
0       4     -1  VL Copenhagen  12    6    3    3    11    10       1  ...   
3       5      0      VL Madrid  12    5    5    2    23    13      10  ...   
6       6     -1      VL Berlin  12    6    2    4    21    11      10  ...   
9       7      1        VL Kiev  12    6    2    4    24    23       1  ...   
12      9      0        VL Bern  12    4    3    5    14    12       2  ...   

    HT_home_goals_y HT_away_goals_y FT_home_goals_y  FT_away_goals_y  \
0                 2               1               3                2   
3                 1               1               2                2   
6                 1               0               2                0   
9                 1               3               1                5   
12                0               0               0                0   

    Sum_Goals_y HT_Results_1_0_2_y  FT_Results_1_0_2_y Under_Over_1.5_y  \
0           5.0                  1                   1                1   
3           4.0                  0                   0                1   
6           2.0                  1                   1                1   
9           6.0                  2                   2                1   
12          0.0                  0                   0                0   

   Under_Over_2.5_y Under_Over_3.5_y  
0                 1                1  
3                 1                1  
6                 0                0  
9                 1                1  
12                0                0  

[5 rows x 58 columns]

In [56]:
datag.columns

colt = ['Season','TC_x','HOMECODE','AWAYCODE','TEAM_x','Team_x','Pos_x', 'Dir_x', 'P', 'W_x', 'D_x', 'L_x', 'GF_x', 'GA_x','DIFF_x',
        'Points_x','TEAM_y','Team_y','Pos_y', 'Dir_y','W_y', 'D_y', 'L_y', 'GF_y', 'GA_y', 'DIFF_y', 'Points_y','HTR_y',
       'FTR_y', 'HT_home_goals_y', 'HT_away_goals_y', 'FT_home_goals_y',
       'FT_away_goals_y', 'Sum_Goals_y', 'HT_Results_1_0_2_y',
       'FT_Results_1_0_2_y', 'Under_Over_1.5_y', 'Under_Over_2.5_y',
       'Under_Over_3.5_y']

col2 = ['HOMECODE','AWAYCODE','Pos_x', 'Dir_x', 'P', 'W_x', 'D_x', 'L_x', 'GF_x', 'GA_x','DIFF_x',
        'Points_x','Pos_y', 'Dir_y','W_y', 'D_y', 'L_y', 'GF_y', 'GA_y', 'DIFF_y', 'Points_y','Under_Over_2.5_y',]

predict1x2 = ['HOMECODE','AWAYCODE','Pos_x', 'Dir_x', 'P', 'W_x', 'D_x', 'L_x', 'GF_x', 'GA_x','DIFF_x',
        'Points_x','Pos_y', 'Dir_y','W_y', 'D_y', 'L_y', 'GF_y', 'GA_y', 'DIFF_y', 'Points_y','FT_Results_1_0_2_y',]
datag.columns

Index(['Pos_x', 'Dir_x', 'Team_x', 'P', 'W_x', 'D_x', 'L_x', 'GF_x', 'GA_x',
       'DIFF_x', 'Points_x', 'Season', 'TEAM_x', 'HOMECODE', 'AWAYCODE_x',
       'TC_x', 'AWAYCODE_y', 'TIMEr_x', 'HTR_x', 'FTR_x', 'HT_home_goals_x',
       'HT_away_goals_x', 'FT_home_goals_x', 'FT_away_goals_x', 'Sum_Goals_x',
       'HT_Results_1_0_2_x', 'FT_Results_1_0_2_x', 'Under_Over_1.5_x',
       'Under_Over_2.5_x', 'Under_Over_3.5_x', 'Pos_y', 'Dir_y', 'Team_y',
       'W_y', 'D_y', 'L_y', 'GF_y', 'GA_y', 'DIFF_y', 'Points_y', 'TEAM_y',
       'HOMECODE_x', 'AWAYCODE', 'TC_y', 'HOMECODE_y', 'TIMEr_y', 'HTR_y',
       'FTR_y', 'HT_home_goals_y', 'HT_away_goals_y', 'FT_home_goals_y',
       'FT_away_goals_y', 'Sum_Goals_y', 'HT_Results_1_0_2_y',
       'FT_Results_1_0_2_y', 'Under_Over_1.5_y', 'Under_Over_2.5_y',
       'Under_Over_3.5_y'],
      dtype='object')

In [57]:
#change collum to change what to predict
datag2 =  datag.reindex(columns= predict1x2)
#datag2.iloc[:, 1:38].head()#[dff2.TEAM == 'VIENNA']
datag2.head()

HOMECODE  AWAYCODE  Pos_x  Dir_x   P  W_x  D_x  L_x  GF_x  GA_x  ...  \
0         12         7      4     -1  12    6    3    3    11    10  ...   
3          1         4      5      0  12    5    5    2    23    13  ...   
6          3         5      6     -1  12    6    2    4    21    11  ...   
9         15         6      7      1  12    6    2    4    24    23  ...   
12        16         8      9      0  12    4    3    5    14    12  ...   

    Pos_y  Dir_y  W_y  D_y  L_y  GF_y  GA_y  DIFF_y  Points_y  \
0      11      1    3    5    4    14    17      -3        14   
3       3      0    7    2    3    19    17       2        23   
6       2      1    7    2    3    22    16       6        23   
9       1     -1    8    1    3    21     9      12        25   
12     13      0    3    3    6    18    19      -1        12   

    FT_Results_1_0_2_y  
0                    1  
3                    0  
6                    1  
9                    2  
12                   0  

[5 rows x 22 columns]

In [58]:
#datag2.iloc[40:140, 1:38]#.head()#[dff2.TEAM == 'VIENNA']

In [59]:
#with open('/home/ideon/Desktop/datag5.csv', 'a') as f:
  #  datag.to_csv(f, index=False, header=True)

In [60]:
mod_data=datag2.reindex(columns=predict1x2).fillna(0)

In [61]:
mod_data.head()

HOMECODE  AWAYCODE  Pos_x  Dir_x   P  W_x  D_x  L_x  GF_x  GA_x  ...  \
0         12         7      4     -1  12    6    3    3    11    10  ...   
3          1         4      5      0  12    5    5    2    23    13  ...   
6          3         5      6     -1  12    6    2    4    21    11  ...   
9         15         6      7      1  12    6    2    4    24    23  ...   
12        16         8      9      0  12    4    3    5    14    12  ...   

    Pos_y  Dir_y  W_y  D_y  L_y  GF_y  GA_y  DIFF_y  Points_y  \
0      11      1    3    5    4    14    17      -3        14   
3       3      0    7    2    3    19    17       2        23   
6       2      1    7    2    3    22    16       6        23   
9       1     -1    8    1    3    21     9      12        25   
12     13      0    3    3    6    18    19      -1        12   

    FT_Results_1_0_2_y  
0                    1  
3                    0  
6                    1  
9                    2  
12                   0  

[5 rows x 22 columns]

In [62]:
t=datag2.shape[0]  # # t is the number of raws
t

6736

In [63]:
#mod_data
dataR=mod_data.values
dataR

array([[12,  7,  4, ..., -3, 14,  1],
       [ 1,  4,  5, ...,  2, 23,  0],
       [ 3,  5,  6, ...,  6, 23,  1],
       ...,
       [15,  4, 14, ...,  5, 41,  0],
       [13,  1, 15, ..., 30, 59,  2],
       [12,  7, 16, ..., 19, 59,  2]])

In [64]:
p1=dataR   # Uncomment when manual is used
p1 

array([[12,  7,  4, ..., -3, 14,  1],
       [ 1,  4,  5, ...,  2, 23,  0],
       [ 3,  5,  6, ...,  6, 23,  1],
       ...,
       [15,  4, 14, ...,  5, 41,  0],
       [13,  1, 15, ..., 30, 59,  2],
       [12,  7, 16, ..., 19, 59,  2]])

In [65]:
X, y = p1[:,:21],p1[:,21:]

In [66]:
X = X.reshape(p1.shape[0], 21)
X = X.astype('float32')

X = X/60
X

array([[ 0.2       ,  0.11666667,  0.06666667, ...,  0.28333333,
        -0.05      ,  0.23333333],
       [ 0.01666667,  0.06666667,  0.08333334, ...,  0.28333333,
         0.03333334,  0.38333333],
       [ 0.05      ,  0.08333334,  0.1       , ...,  0.26666668,
         0.1       ,  0.38333333],
       ...,
       [ 0.25      ,  0.06666667,  0.23333333, ...,  0.6666667 ,
         0.08333334,  0.68333334],
       [ 0.21666667,  0.01666667,  0.25      , ...,  0.55      ,
         0.5       ,  0.98333335],
       [ 0.2       ,  0.11666667,  0.26666668, ...,  0.41666666,
         0.31666666,  0.98333335]], dtype=float32)

In [67]:
X.shape

(6736, 21)

In [68]:
import numpy as np
from sklearn.model_selection import train_test_split

In [69]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

In [70]:
X_train

array([[ 0.21666667,  0.01666667,  0.21666667, ...,  0.23333333,
         0.15      ,  0.28333333],
       [ 0.13333334,  0.03333334,  0.2       , ...,  0.31666666,
         0.53333336,  0.98333335],
       [ 0.1       ,  0.15      ,  0.11666667, ...,  0.5833333 ,
        -0.28333333,  0.51666665],
       ...,
       [ 0.15      ,  0.06666667,  0.13333334, ...,  0.41666666,
         0.35      ,  0.7       ],
       [ 0.2       ,  0.08333334,  0.25      , ...,  0.36666667,
        -0.03333334,  0.25      ],
       [ 0.11666667,  0.2       ,  0.13333334, ...,  0.28333333,
        -0.08333334,  0.28333333]], dtype=float32)

In [71]:
X_test

array([[ 0.16666667,  0.18333334,  0.2       , ...,  0.55      ,
        -0.28333333,  0.16666667],
       [ 0.18333334,  0.03333334,  0.15      , ...,  0.5833333 ,
         0.18333334,  0.75      ],
       [ 0.23333333,  0.25      ,  0.1       , ...,  0.06666667,
        -0.01666667,  0.06666667],
       ...,
       [ 0.1       ,  0.16666667,  0.15      , ...,  0.15      ,
        -0.03333334,  0.13333334],
       [ 0.1       ,  0.05      ,  0.15      , ...,  0.35      ,
         0.18333334,  0.6333333 ],
       [ 0.16666667,  0.08333334,  0.18333334, ...,  0.4       ,
         0.3       ,  0.6333333 ]], dtype=float32)

In [72]:
y_train

array([[0],
       [0],
       [0],
       ...,
       [0],
       [0],
       [2]])

In [73]:
y_test

array([[1],
       [2],
       [0],
       ...,
       [0],
       [2],
       [0]])

In [74]:
from keras.utils import np_utils
NB_CLASSES =3
import numpy as np
y_train = np_utils.to_categorical(y_train, NB_CLASSES)
y_test = np_utils.to_categorical(y_test, NB_CLASSES)

In [75]:
y_train

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)

In [76]:
y_train

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.]], dtype=float32)