In [1]:
import numpy as np
import pandas as pd

In [2]:
#RAW DATA FROM SCRAPPIN
df= pd.read_csv('/home/gibeon/Desktop/MY/fvldata/STORAGE/clean_data/pTable001.csv')

#df['Pos'] = df.index
#df.reset_index(level=0, inplace=True)

#df['INDX'] = pd.Series(list(range(len(df['Team']))))
df.head()    ####  REMOVE DIFF,one of WDL,

Pos  Dir           Team  P  W  D  L  GF  GA  DIFF  Points        Season
0    1    0  VL Copenhagen  1  1  0  0   3   1     2       3  Season 12787
1    2    0   VL Amsterdam  1  1  0  0   2   0     2       3  Season 12787
2    3    0      VL Ankara  1  1  0  0   2   0     2       3  Season 12787
3    4    0        VL Kiev  1  1  0  0   3   2     1       3  Season 12787
4    5    0      VL Zagreb  1  1  0  0   2   1     1       3  Season 12787

In [3]:
# df2 = df.set_index(['P', 'Pos'],drop=False)  ##interesing stuff
# df2.head()


In [4]:
#df.head()
df['Team'].unique()

array(['VL Copenhagen', 'VL Amsterdam', 'VL Ankara', 'VL Kiev',
       'VL Zagreb', 'VL Berlin', 'VL Vienna', 'VL Madrid', 'VL Moscow',
       'VL Lisbon', 'VL Prague', 'VL Rome', 'VL Athens', 'VL London',
       'VL Bern', 'VL Paris'], dtype=object)

In [5]:
def teamCoded(S):
    
#     cats=['MADRID', 'AMSTERDAM','BERLIN','LONDON','ROME','OSLO','LISBON','PARIS','BRUSSELS','ATHENS','STOCKHOLM',
#           'COPENHAGEN','VIENNA', 'ANKARA','EDINBURGH','BERN']
    
    cats=['MADRID', 'AMSTERDAM','BERLIN','LONDON','ROME','MOSCOW','LISBON','PARIS','ZAGREB','ATHENS','PRAGUE',
          'COPENHAGEN','VIENNA', 'ANKARA','KIEV','BERN']

    catsRev=[]
    for tm in S:
        if tm == cats[0]:
            catsRev.append(1)
        elif tm == cats[1]:
            catsRev.append(2)
        elif tm == cats[2]:
            catsRev.append(3)
        elif tm == cats[3]:
            catsRev.append(4)
        elif tm == cats[4]:
            catsRev.append(5)
        elif tm == cats[5]:
            catsRev.append(6)
        elif tm == cats[6]:
            catsRev.append(7)
        elif tm == cats[7]:
            catsRev.append(8)
        elif tm == cats[8]:
            catsRev.append(9)
        elif tm == cats[9]:
            catsRev.append(10)
        elif tm == cats[10]:
            catsRev.append(11)
        elif tm == cats[11]:
            catsRev.append(12)
        elif tm == cats[12]:
            catsRev.append(13)
        elif tm == cats[13]:
            catsRev.append(14)
        elif tm == cats[14]:
            catsRev.append(15)
        elif tm == cats[15]:
            catsRev.append(16)
    return catsRev


df['TEAM']=pd.Series([x.split()[1].upper() for x in df.Team])
df['HOMECODE']=teamCoded(df['TEAM'])
df['AWAYCODE']=teamCoded(df['TEAM'])

In [6]:
df.head()

Pos  Dir           Team  P  W  D  L  GF  GA  DIFF  Points        Season  \
0    1    0  VL Copenhagen  1  1  0  0   3   1     2       3  Season 12787   
1    2    0   VL Amsterdam  1  1  0  0   2   0     2       3  Season 12787   
2    3    0      VL Ankara  1  1  0  0   2   0     2       3  Season 12787   
3    4    0        VL Kiev  1  1  0  0   3   2     1       3  Season 12787   
4    5    0      VL Zagreb  1  1  0  0   2   1     1       3  Season 12787   

         TEAM  HOMECODE  AWAYCODE  
0  COPENHAGEN        12        12  
1   AMSTERDAM         2         2  
2      ANKARA        14        14  
3        KIEV        15        15  
4      ZAGREB         9         9

In [7]:
df1 = df[df.isna().any(axis=1)]

In [8]:
df1

Empty DataFrame
Columns: [Pos, Dir, Team, P, W, D, L, GF, GA, DIFF, Points, Season, TEAM, HOMECODE, AWAYCODE]
Index: []

In [9]:
dfR= pd.read_csv('/home/gibeon/Desktop/MY/fvldata/STORAGE/clean_data/pResu001.csv')

#dfR= pd.read_csv('/home/ideon/Desktop/DATA CENTRE/resultDataR.csv')
dfR.head()

TIMER                       TEAMSr   HTR   FTR  P        Season
0  27/07/2019 10:50  VL Copenhagen  -  VL London  2:01  3:01  1  Season 12787
1  27/07/2019 10:50      VL Berlin  -  VL Athens  1:00  1:00  1  Season 12787
2  27/07/2019 10:50      VL Lisbon  -  VL Moscow  0:00  0:00  1  Season 12787
3  27/07/2019 10:50       VL Ankara  -  VL Paris  0:00  2:00  1  Season 12787
4  27/07/2019 10:50        VL Prague  -  VL Kiev  0:03  2:03  1  Season 12787

In [10]:


#function to input(ps) DF column of form/content (3:2) eg HT result or HT results and out put ps.series with eithe 0,1 or 2
def results(ps):

    #ps = ps.dropna()
    lp=[]
    for x in ps:
       # print(x)
        
        h=x.replace(':','  ')[:1]
      #  print(h)
        a=x.replace(':','  ')[1:]
        if float(h) > float(a):
            lp.append(1)

        elif float(a) > float(h):
            lp.append(2)
        else:
            lp.append(0)

    return pd.Series(lp)



def over_under(ps,n):
    lp=[]
    for x in ps:
        h=x.replace(':','  ')[:1]
        a=x.replace(':','  ')[1:]
        # if goals sum is greater than n value is 1
        
        if (float(h) + float(a)) > float(n):
            lp.append(1)

        else:
            #means it is under n eg under 2.5
            lp.append(0)

    return pd.Series(lp)

##addition collumn of all goals
def goalsum(ps):
    lp=[]
    for x in ps:
        h=x.replace(':','  ')[:1]
        a=x.replace(':','  ')[1:]
        # if goals sum is greater than n value is 1
        
        lp.append((float(h) + float(a)))

    return pd.Series(lp)

In [11]:
#======================================================================
dfR['TEAMSr']
dfR['TEAMSr']=pd.Series([x.upper() for x in dfR.TEAMSr])
dfR['TEAMSr']=pd.Series([x.upper() for x in dfR.TEAMSr])
#split TEAMS into HOME & AWAY 
dfR['HOME']=pd.Series([x.split()[1] for x in dfR.TEAMSr]) 
dfR['AWAY']=pd.Series([x.split()[4] for x in dfR.TEAMSr])

dfR['TIMEr']=pd.Series([x.split()[1] for x in dfR.TIMER])
#Use teamCode FX to code HOME & AWAY collumns and crean new HOMECODE & AWAYCODE
dfR['TC']=dfR['HOME']+' '+dfR['AWAY']

dfR['HOMECODE']=teamCoded(dfR['HOME'])
dfR['AWAYCODE']=teamCoded(dfR['AWAY'])
#dfR['TEAMSC']=dfR['HOMECODE'] + dfR['AWAYCODE']
#teamCode(dfR['HOME'])


    
dfR['FT_Goals']=pd.Series([str(x).replace(':','  ')[:] for x in dfR.FTR])
dfR['HT_Goals']=pd.Series([str(x).replace(':','  ')[:] for x in dfR.HTR])
dfR['FT_home_goals']=pd.Series([str(x).replace(':','  ')[:1] for x in dfR.FTR])
dfR['FT_away_goals']=pd.Series([str(x).replace(':','  ')[1:] for x in dfR.FTR])
dfR['HT_home_goals']=pd.Series([str(x).replace(':','  ')[:1] for x in dfR.HTR])
dfR['HT_away_goals']=pd.Series([str(x).replace(':','  ')[1:] for x in dfR.HTR])



dfR['FT_Results_1_0_2']=results(dfR['FT_Goals'])
dfR['HT_Results_1_0_2']=results(dfR['HT_Goals'])


# FT UNDER /OVER Goals
p = 3.5
n = 2.5
q = 1.5

dfR['Under_Over_3.5']= over_under(dfR['FT_Goals'],p)
dfR['Under_Over_2.5']= over_under(dfR['FT_Goals'],n)
dfR['Under_Over_1.5']= over_under(dfR['FT_Goals'],q)



dfR['Sum_Goals']= goalsum(dfR['FT_Goals'])





dfR['Sum_Goals']= goalsum(dfR['FT_Goals'])# addition column of all goals

#dfR['HT_Results_1_0_2']=results(dfR['HT_Goals'])

colum=['P','Season','TC','HOMECODE', 'AWAYCODE','TIMEr','HTR', 'FTR', 'HT_home_goals', 'HT_away_goals',
       'FT_home_goals','FT_away_goals','Sum_Goals','HT_Results_1_0_2','FT_Results_1_0_2','Under_Over_1.5','Under_Over_2.5',
       'Under_Over_3.5']
resu= dfR.reindex(columns=colum).fillna(0)#.values


colum=['TC','HOMECODE', 'AWAYCODE','TIMEr','HTR', 'FTR', 'HT_home_goals', 'HT_away_goals',
       'FT_home_goals','FT_away_goals','HT_Results_1_0_2','FT_Results_1_0_2','TIMER','TIMED','1','2','X','HT1','HT2','HTX','FS (0:0)','FS(0:0)2','FS(0:0)X','G(0.5)O','G(0.5)U',
         'G(1.5)O','G(1.5)U','G(2.5)O','G(2.5)U','G(3.5)O','G(3.5)U','G(4.5)O','G(4.5)U','Under_Over_1.5','Under_Over_2.5',
       'Under_Over_3.5']

In [12]:
resu.head()

P        Season                 TC  HOMECODE  AWAYCODE  TIMEr   HTR   FTR  \
0  1  Season 12787  COPENHAGEN LONDON        12         4  10:50  2:01  3:01   
1  1  Season 12787      BERLIN ATHENS         3        10  10:50  1:00  1:00   
2  1  Season 12787      LISBON MOSCOW         7         6  10:50  0:00  0:00   
3  1  Season 12787       ANKARA PARIS        14         8  10:50  0:00  2:00   
4  1  Season 12787        PRAGUE KIEV        11        15  10:50  0:03  2:03   

  HT_home_goals HT_away_goals FT_home_goals FT_away_goals  Sum_Goals  \
0             2            01             3            01        4.0   
1             1            00             1            00        1.0   
2             0            00             0            00        0.0   
3             0            00             2            00        2.0   
4             0            03             2            03        5.0   

   HT_Results_1_0_2  FT_Results_1_0_2  Under_Over_1.5  Under_Over_2.5  \
0                 1                 1               1               1   
1                 1                 1               0               0   
2                 0                 0               0               0   
3                 0                 1               1               0   
4                 2                 2               1               1   

   Under_Over_3.5  
0               1  
1               0  
2               0  
3               0  
4               1

In [13]:
#gr = resu.groupby([resu['HOMECODE'], resu['AWAYCODE']])

In [ ]:
#gr # what the f*ck is this pandas object

In [14]:
df['P']=df['P']+1

In [15]:
df.head()

Pos  Dir           Team  P  W  D  L  GF  GA  DIFF  Points        Season  \
0    1    0  VL Copenhagen  2  1  0  0   3   1     2       3  Season 12787   
1    2    0   VL Amsterdam  2  1  0  0   2   0     2       3  Season 12787   
2    3    0      VL Ankara  2  1  0  0   2   0     2       3  Season 12787   
3    4    0        VL Kiev  2  1  0  0   3   2     1       3  Season 12787   
4    5    0      VL Zagreb  2  1  0  0   2   1     1       3  Season 12787   

         TEAM  HOMECODE  AWAYCODE  
0  COPENHAGEN        12        12  
1   AMSTERDAM         2         2  
2      ANKARA        14        14  
3        KIEV        15        15  
4      ZAGREB         9         9

In [16]:
##magic happens here

dff1 = pd.merge(df,resu, on =('Season','P','HOMECODE'))#,by='Season')#,left_on='lkey', right_on='rkey')
#dff1['AWAYCODE'] = dff1['AWAYCODE_x']
dff2 = pd.merge(df,resu, on =('Season','P','AWAYCODE'))#,left_on='lkey', right_on='rkey') 

In [17]:
dff1.sort_values(by=['Season','P'])
dff1 = dff1.drop_duplicates()
dff1.head()

Pos  Dir          Team  P  W  D  L  GF  GA  DIFF  ...  HT_home_goals  \
0    2    0  VL Amsterdam  2  1  0  0   2   0     2  ...              0   
1    4    0       VL Kiev  2  1  0  0   3   2     1  ...              0   
2    7    0     VL Vienna  2  0  1  0   2   2     0  ...              0   
3    9    0     VL Moscow  2  0  1  0   0   0     0  ...              1   
4   12    0       VL Rome  2  0  0  1   1   2    -1  ...              0   

  HT_away_goals FT_home_goals  FT_away_goals  Sum_Goals HT_Results_1_0_2  \
0            00             0             01        1.0                0   
1            01             0             01        1.0                2   
2            00             1             00        1.0                0   
3            01             3             01        4.0                0   
4            00             0             00        0.0                0   

   FT_Results_1_0_2 Under_Over_1.5 Under_Over_2.5 Under_Over_3.5  
0                 2              0              0              0  
1                 2              0              0              0  
2                 1              0              0              0  
3                 1              1              1              1  
4                 0              0              0              0  

[5 rows x 30 columns]

In [18]:
dff2.sort_values(by=['Season','P'])
dff2 = dff2.drop_duplicates()
dff2.head()

Pos  Dir           Team  P  W  D  L  GF  GA  DIFF  ...  HT_home_goals  \
0    1    0  VL Copenhagen  2  1  0  0   3   1     2  ...              0   
1    3    0      VL Ankara  2  1  0  0   2   0     2  ...              1   
2    5    0      VL Zagreb  2  1  0  0   2   1     1  ...              2   
3    6    0      VL Berlin  2  1  0  0   1   0     1  ...              1   
4    8    0      VL Madrid  2  0  1  0   2   2     0  ...              0   

  HT_away_goals FT_home_goals  FT_away_goals  Sum_Goals HT_Results_1_0_2  \
0            01             0             01        1.0                2   
1            00             1             00        1.0                1   
2            00             3             00        3.0                1   
3            01             3             01        4.0                0   
4            00             1             01        2.0                0   

   FT_Results_1_0_2 Under_Over_1.5 Under_Over_2.5 Under_Over_3.5  
0                 2              0              0              0  
1                 1              0              0              0  
2                 1              1              1              0  
3                 1              1              1              1  
4                 0              1              0              0  

[5 rows x 30 columns]

In [19]:
#dff1.iloc[:, 1:82]#[dff1.TEAM == 'MADRID']  #  most IMPORTANT FILTER OF DFS....NOTE NOTE NOTE
#len(dff1.columns)#[data.three > 5]
#len(dff1.columns)

dff1.iloc[:, 1:20]#[dff1.TEAM == 'MADRID']

Dir           Team   P   W   D   L  GF  GA  DIFF  Points        Season  \
0        0   VL Amsterdam   2   1   0   0   2   0     2       3  Season 12787   
1        0        VL Kiev   2   1   0   0   3   2     1       3  Season 12787   
2        0      VL Vienna   2   0   1   0   2   2     0       1  Season 12787   
3        0      VL Moscow   2   0   1   0   0   0     0       1  Season 12787   
4        0        VL Rome   2   0   0   1   1   2    -1       0  Season 12787   
5        0      VL Athens   2   0   0   1   0   1    -1       0  Season 12787   
6        0      VL London   2   0   0   1   1   3    -2       0  Season 12787   
7        0       VL Paris   2   0   0   1   0   2    -2       0  Season 12787   
8        0  VL Copenhagen   3   2   0   0   4   1     3       6  Season 12787   
9        1      VL Ankara   3   1   0   1   2   1     1       3  Season 12787   
10       1      VL Berlin   3   1   0   1   2   3    -1       3  Season 12787   
11       1      VL Zagreb   3   1   0   1   2   4    -2       3  Season 12787   
12       1      VL Madrid   3   0   2   0   3   3     0       2  Season 12787   
13       1        VL Rome   3   0   1   1   1   2    -1       1  Season 12787   
14       1      VL Lisbon   3   0   1   1   0   1    -1       1  Season 12787   
15       1        VL Bern   3   0   1   1   0   2    -2       1  Season 12787   
16       1      VL Vienna   4   1   2   0   4   3     1       5  Season 12787   
17       1      VL Moscow   4   1   1   1   3   2     1       4  Season 12787   
18      -1      VL Athens   4   1   1   1   1   1     0       4  Season 12787   
19      -1      VL London   4   1   1   1   3   4    -1       4  Season 12787   
20       1   VL Amsterdam   4   1   0   2   2   2     0       3  Season 12787   
21       1      VL Prague   4   1   0   2   3   4    -1       3  Season 12787   
22       1       VL Paris   4   1   0   2   3   4    -1       3  Season 12787   
23       1        VL Kiev   4   1   0   2   3   9    -6       3  Season 12787   
24       1      VL Ankara   5   2   1   1   3   1     2       7  Season 12787   
25       1      VL Madrid   5   1   2   1  10   9     1       5  Season 12787   
26       1        VL Rome   5   1   2   1   4   4     0       5  Season 12787   
27      -1       VL Paris   5   1   1   2   5   6    -1       4  Season 12787   
28       1        VL Bern   5   1   1   2   2   4    -2       4  Season 12787   
29       1      VL Berlin   5   1   1   2   3   7    -4       4  Season 12787   
...    ...            ...  ..  ..  ..  ..  ..  ..   ...     ...           ...   
13250    0   VL Amsterdam  27  14   5   7  45  33    12      47  Season 12628   
13251    0      VL Moscow  27  13   7   6  40  24    16      46  Season 12628   
13252    0      VL Ankara  27  11   2  13  32  39    -7      35  Season 12628   
13253    1      VL London  27  10   4  12  37  35     2      34  Season 12628   
13254    0        VL Bern  27   8   5  13  32  42   -10      29  Season 12628   
13255   -1      VL Athens  27   7   3  16  26  47   -21      24  Season 12628   
13256    0      VL Berlin  28  17   3   7  49  28    21      54  Season 12628   
13257   -1        VL Rome  28  15   3   9  44  32    12      48  Season 12628   
13258    0      VL Prague  28  10   5  12  37  45    -8      35  Season 12628   
13259    0      VL Ankara  28  11   2  14  32  40    -8      35  Season 12628   
13260    0      VL Vienna  28   7   5  15  19  36   -17      26  Season 12628   
13261   -1       VL Paris  28   6   7  14  32  46   -14      25  Season 12628   
13262    1  VL Copenhagen  28   7   4  16  19  37   -18      25  Season 12628   
13263   -1        VL Kiev  28   7   3  17  34  52   -18      24  Season 12628   
13264    0      VL Madrid  29  15   8   5  56  31    25      53  Season 12628   
13265   -1   VL Amsterdam  29  16   5   7  49  33    16      53  Season 12628   
13266    1      VL Lisbon  29  16   5   7  38  23    15      53  Season 12628   
13267    0      VL Moscow  29  13   7 

In [20]:
#dff2.iloc[:, 31:52]#[data.three > 5]
#len(dff1.columns)
dff2['HOMECODE'] = dff2['HOMECODE_y']#//couse by duplicate files
#dff2.iloc[:, 1:82]#[dff2.TEAM == 'VIENNA']

In [21]:
datag = pd.merge(dff1,dff2, on =('Season','P','HOMECODE'))

In [22]:
datag.sort_values(by=['Season','P'])
datag = datag.drop_duplicates()
datag

Pos_x  Dir_x         Team_x   P  W_x  D_x  L_x  GF_x  GA_x  DIFF_x  \
0          2      0   VL Amsterdam   2    1    0    0     2     0       2   
1          4      0        VL Kiev   2    1    0    0     3     2       1   
2          7      0      VL Vienna   2    0    1    0     2     2       0   
3          9      0      VL Moscow   2    0    1    0     0     0       0   
4         12      0        VL Rome   2    0    0    1     1     2      -1   
5         13      0      VL Athens   2    0    0    1     0     1      -1   
6         14      0      VL London   2    0    0    1     1     3      -2   
7         16      0       VL Paris   2    0    0    1     0     2      -2   
8          1      0  VL Copenhagen   3    2    0    0     4     1       3   
9          6      1      VL Ankara   3    1    0    1     2     1       1   
10        10      1      VL Berlin   3    1    0    1     2     3      -1   
11        11      1      VL Zagreb   3    1    0    1     2     4      -2   
12        12      1      VL Madrid   3    0    2    0     3     3       0   
13        13      1        VL Rome   3    0    1    1     1     2      -1   
14        14      1      VL Lisbon   3    0    1    1     0     1      -1   
15        16      1        VL Bern   3    0    1    1     0     2      -2   
16         4      1      VL Vienna   4    1    2    0     4     3       1   
17         5      1      VL Moscow   4    1    1    1     3     2       1   
18         8     -1      VL Athens   4    1    1    1     1     1       0   
19         9     -1      VL London   4    1    1    1     3     4      -1   
20        12      1   VL Amsterdam   4    1    0    2     2     2       0   
21        13      1      VL Prague   4    1    0    2     3     4      -1   
22        14      1       VL Paris   4    1    0    2     3     4      -1   
23        15      1        VL Kiev   4    1    0    2     3     9      -6   
24         4      1      VL Ankara   5    2    1    1     3     1       2   
25         9      1      VL Madrid   5    1    2    1    10     9       1   
26        10      1        VL Rome   5    1    2    1     4     4       0   
27        12     -1       VL Paris   5    1    1    2     5     6      -1   
28        13      1        VL Bern   5    1    1    2     2     4      -2   
29        14      1      VL Berlin   5    1    1    2     3     7      -4   
...      ...    ...            ...  ..  ...  ...  ...   ...   ...     ...   
13226      4      0   VL Amsterdam  27   14    5    7    45    33      12   
13227      5      0      VL Moscow  27   13    7    6    40    24      16   
13228      9      0      VL Ankara  27   11    2   13    32    39      -7   
13229     10      1      VL London  27   10    4   12    37    35       2   
13230     11      0        VL Bern  27    8    5   13    32    42     -10   
13231     14     -1      VL Athens  27    7    3   16    26    47     -21   
13232      1      0      VL Berlin  28   17    3    7    49    28      21   
13233      5     -1        VL Rome  28   15    3    9    44    32      12   
13234      8      0      VL Prague  28   10    5   12    37    45      -8   
13235      9      0      VL Ankara  28   11    2   14    32    40      -8   
13236     12      0      VL Vienna  28    7    5   15    19    36     -17   
13237     13     -1       VL Paris  28    6    7   14    32    46     -14   
13238     14      1  VL Copenhagen  28    7    4   16    19    37     -18   
13239     15     -1        VL Kiev  28    7    3   17    34    52     -18   
13240      2      0      VL Madrid  29   15    8    5    56    31      25   
13241      3     -1   VL Amsterdam  29   16    5    7    49    33      16   
13242      4      1      VL Lisbon  29   16    5    7    38    23      15   
13243      6      0      VL Moscow  29   13    7    8    40    26      14   
13244      7      0      VL Zagreb  29   12   10    6    38    26      12   
13245      9     -1      VL London  29   11    4   13    40    38       2   
132

In [23]:
datag.head()

Pos_x  Dir_x        Team_x  P  W_x  D_x  L_x  GF_x  GA_x  DIFF_x  ...  \
0      2      0  VL Amsterdam  2    1    0    0     2     0       2  ...   
1      4      0       VL Kiev  2    1    0    0     3     2       1  ...   
2      7      0     VL Vienna  2    0    1    0     2     2       0  ...   
3      9      0     VL Moscow  2    0    1    0     0     0       0  ...   
4     12      0       VL Rome  2    0    0    1     1     2      -1  ...   

   HT_home_goals_y HT_away_goals_y FT_home_goals_y  FT_away_goals_y  \
0                0              00               0               01   
1                0              01               0               01   
2                0              00               1               00   
3                1              01               3               01   
4                0              00               0               00   

   Sum_Goals_y HT_Results_1_0_2_y  FT_Results_1_0_2_y Under_Over_1.5_y  \
0          1.0                  0                   2                0   
1          1.0                  2                   2                0   
2          1.0                  0                   1                0   
3          4.0                  0                   1                1   
4          0.0                  0                   0                0   

  Under_Over_2.5_y Under_Over_3.5_y  
0                0                0  
1                0                0  
2                0                0  
3                1                1  
4                0                0  

[5 rows x 58 columns]

In [24]:
datag.columns

colt = ['Season','TC_x','HOMECODE','AWAYCODE','TEAM_x','Team_x','Pos_x', 'Dir_x', 'P', 'W_x', 'D_x', 'L_x', 'GF_x', 'GA_x','DIFF_x',
        'Points_x','TEAM_y','Team_y','Pos_y', 'Dir_y','W_y', 'D_y', 'L_y', 'GF_y', 'GA_y', 'DIFF_y', 'Points_y','HTR_y',
       'FTR_y', 'HT_home_goals_y', 'HT_away_goals_y', 'FT_home_goals_y',
       'FT_away_goals_y', 'Sum_Goals_y', 'HT_Results_1_0_2_y',
       'FT_Results_1_0_2_y', 'Under_Over_1.5_y', 'Under_Over_2.5_y',
       'Under_Over_3.5_y']

col2 = ['HOMECODE','AWAYCODE','Pos_x', 'Dir_x', 'P', 'W_x', 'D_x', 'L_x', 'GF_x', 'GA_x','DIFF_x',
        'Points_x','Pos_y', 'Dir_y','W_y', 'D_y', 'L_y', 'GF_y', 'GA_y', 'DIFF_y', 'Points_y','Under_Over_2.5_y',]

predict1x2 = ['HOMECODE','AWAYCODE','Pos_x', 'Dir_x', 'P', 'W_x', 'D_x', 'L_x', 'GF_x', 'GA_x','DIFF_x',
        'Points_x','Pos_y', 'Dir_y','W_y', 'D_y', 'L_y', 'GF_y', 'GA_y', 'DIFF_y', 'Points_y','FT_Results_1_0_2_y',]
datag.columns

Index(['Pos_x', 'Dir_x', 'Team_x', 'P', 'W_x', 'D_x', 'L_x', 'GF_x', 'GA_x',
       'DIFF_x', 'Points_x', 'Season', 'TEAM_x', 'HOMECODE', 'AWAYCODE_x',
       'TC_x', 'AWAYCODE_y', 'TIMEr_x', 'HTR_x', 'FTR_x', 'HT_home_goals_x',
       'HT_away_goals_x', 'FT_home_goals_x', 'FT_away_goals_x', 'Sum_Goals_x',
       'HT_Results_1_0_2_x', 'FT_Results_1_0_2_x', 'Under_Over_1.5_x',
       'Under_Over_2.5_x', 'Under_Over_3.5_x', 'Pos_y', 'Dir_y', 'Team_y',
       'W_y', 'D_y', 'L_y', 'GF_y', 'GA_y', 'DIFF_y', 'Points_y', 'TEAM_y',
       'HOMECODE_x', 'AWAYCODE', 'TC_y', 'HOMECODE_y', 'TIMEr_y', 'HTR_y',
       'FTR_y', 'HT_home_goals_y', 'HT_away_goals_y', 'FT_home_goals_y',
       'FT_away_goals_y', 'Sum_Goals_y', 'HT_Results_1_0_2_y',
       'FT_Results_1_0_2_y', 'Under_Over_1.5_y', 'Under_Over_2.5_y',
       'Under_Over_3.5_y'],
      dtype='object')

In [25]:
#change collum to change what to predict
datag2 =  datag.reindex(columns= predict1x2)
#datag2.iloc[:, 1:38].head()#[dff2.TEAM == 'VIENNA']
datag2.head()

HOMECODE  AWAYCODE  Pos_x  Dir_x  P  W_x  D_x  L_x  GF_x  GA_x  ...  Pos_y  \
0         2        11      2      0  2    1    0    0     2     0  ...     11   
1        15        12      4      0  2    1    0    0     3     2  ...      1   
2        13         7      7      0  2    0    1    0     2     2  ...     10   
3         6         3      9      0  2    0    1    0     0     0  ...      6   
4         5        16     12      0  2    0    0    1     1     2  ...     15   

   Dir_y  W_y  D_y  L_y  GF_y  GA_y  DIFF_y  Points_y  FT_Results_1_0_2_y  
0      0    0    0    1     2     3      -1         0                   2  
1      0    1    0    0     3     1       2         3                   2  
2      0    0    1    0     0     0       0         1                   1  
3      0    1    0    0     1     0       1         3                   1  
4      0    0    0    1     0     2      -2         0                   0  

[5 rows x 22 columns]

In [26]:
#datag2.iloc[40:140, 1:38]#.head()#[dff2.TEAM == 'VIENNA']

In [27]:
#with open('/home/ideon/Desktop/datag5.csv', 'a') as f:
  #  datag.to_csv(f, index=False, header=True)

In [28]:
mod_data=datag2.reindex(columns=predict1x2).fillna(0)

In [29]:
mod_data.head()

HOMECODE  AWAYCODE  Pos_x  Dir_x  P  W_x  D_x  L_x  GF_x  GA_x  ...  Pos_y  \
0         2        11      2      0  2    1    0    0     2     0  ...     11   
1        15        12      4      0  2    1    0    0     3     2  ...      1   
2        13         7      7      0  2    0    1    0     2     2  ...     10   
3         6         3      9      0  2    0    1    0     0     0  ...      6   
4         5        16     12      0  2    0    0    1     1     2  ...     15   

   Dir_y  W_y  D_y  L_y  GF_y  GA_y  DIFF_y  Points_y  FT_Results_1_0_2_y  
0      0    0    0    1     2     3      -1         0                   2  
1      0    1    0    0     3     1       2         3                   2  
2      0    0    1    0     0     0       0         1                   1  
3      0    1    0    0     1     0       1         3                   1  
4      0    0    0    1     0     2      -2         0                   0  

[5 rows x 22 columns]

In [30]:
t=datag2.shape[0]  # # t is the number of raws
t

13256

In [31]:
#mod_data
dataR=mod_data.values
dataR

array([[ 2, 11,  2, ..., -1,  0,  2],
       [15, 12,  4, ...,  2,  3,  2],
       [13,  7,  7, ...,  0,  1,  1],
       ...,
       [15,  4, 14, ...,  5, 40,  0],
       [13,  1, 15, ..., 27, 56,  2],
       [12,  7, 16, ..., 18, 56,  2]])

In [32]:
p1=dataR   # Uncomment when manual is used
p1 

array([[ 2, 11,  2, ..., -1,  0,  2],
       [15, 12,  4, ...,  2,  3,  2],
       [13,  7,  7, ...,  0,  1,  1],
       ...,
       [15,  4, 14, ...,  5, 40,  0],
       [13,  1, 15, ..., 27, 56,  2],
       [12,  7, 16, ..., 18, 56,  2]])

In [33]:
X, y = p1[:,:21],p1[:,21:]

In [34]:
X = X.reshape(p1.shape[0], 21)
X = X.astype('float32')

X = X/60
X

array([[ 0.03333334,  0.18333334,  0.03333334, ...,  0.05      ,
        -0.01666667,  0.        ],
       [ 0.25      ,  0.2       ,  0.06666667, ...,  0.01666667,
         0.03333334,  0.05      ],
       [ 0.21666667,  0.11666667,  0.11666667, ...,  0.        ,
         0.        ,  0.01666667],
       ...,
       [ 0.25      ,  0.06666667,  0.23333333, ...,  0.6333333 ,
         0.08333334,  0.6666667 ],
       [ 0.21666667,  0.01666667,  0.25      , ...,  0.55      ,
         0.45      ,  0.93333334],
       [ 0.2       ,  0.11666667,  0.26666668, ...,  0.41666666,
         0.3       ,  0.93333334]], dtype=float32)

In [35]:
X.shape

(13256, 21)

In [36]:
import numpy as np
from sklearn.model_selection import train_test_split

In [37]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

In [78]:
X_train

array([[ 0.13333334,  0.73333335,  0.13333334, ...,  0.2       ,
        -0.06666667,  0.        ],
       [ 1.        ,  0.8       ,  0.26666668, ...,  0.06666667,
         0.13333334,  0.2       ],
       [ 0.8666667 ,  0.46666667,  0.46666667, ...,  0.        ,
         0.        ,  0.06666667],
       ...,
       [ 0.6       ,  0.2       ,  0.33333334, ...,  0.06666667,
         0.        ,  0.06666667],
       [ 0.4       ,  0.33333334,  0.4       , ...,  0.13333334,
        -0.06666667,  0.        ],
       [ 0.93333334,  0.73333335,  0.46666667, ...,  0.2       ,
        -0.13333334,  0.        ]], dtype=float32)

In [39]:
X_test

array([[ 0.01666667,  0.11666667,  0.03333334, ...,  0.51666665,
        -0.08333334,  0.5       ],
       [ 0.23333333,  0.21666667,  0.23333333, ...,  0.3       ,
        -0.11666667,  0.23333333],
       [ 0.05      ,  0.16666667,  0.11666667, ...,  0.2       ,
        -0.13333334,  0.06666667],
       ...,
       [ 0.26666668,  0.01666667,  0.21666667, ...,  0.08333334,
         0.13333334,  0.25      ],
       [ 0.15      ,  0.01666667,  0.1       , ...,  0.13333334,
         0.28333333,  0.41666666],
       [ 0.21666667,  0.15      ,  0.25      , ...,  0.33333334,
         0.01666667,  0.48333332]], dtype=float32)

In [79]:
y_train

array([2, 2, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 2, 1, 0, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 2, 2, 1, 0, 1, 1, 1, 2, 1, 1, 1, 2, 0, 1, 1, 1, 1,
       2, 0, 2, 2, 1, 2, 2, 1, 2, 0, 2, 1, 1, 1, 0, 1, 2, 1, 0, 2, 1, 2,
       2, 2, 0, 1, 2, 1, 1, 1, 1, 0, 2, 1, 1, 2, 1, 0, 2, 0, 2, 2, 2, 0,
       1, 2, 2, 2, 1, 2, 0, 1, 2, 0, 2, 1, 2, 0, 2, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 0, 2, 0, 0, 2, 0, 0, 0, 1, 0, 1, 1, 2, 1, 1, 1, 1, 0,
       1, 2, 2, 1, 1, 2, 0, 1, 1, 0, 1, 2, 1, 2, 2, 2, 1, 2, 1, 1, 0, 0,
       0, 2, 2, 0, 2, 1, 1, 1, 2, 0, 0, 0, 1, 0, 1, 2, 0, 2, 1, 2, 2, 1,
       1, 1, 1, 2, 2, 1, 2, 1, 0, 1, 1, 1, 1, 2, 1, 2, 0, 1, 0, 2, 2, 1,
       1, 1, 0, 0, 0, 2, 0, 0, 2, 2, 2, 1, 1, 1, 2, 1, 0, 1, 2, 1, 1, 1,
       1, 1, 2, 1, 0, 1, 1, 0, 1, 2, 2, 1, 1, 1, 0, 1, 0, 1, 0, 2, 0, 1,
       2, 0, 2, 0, 1, 2, 0, 1, 1, 1, 2, 0, 0, 1, 0, 1, 2, 1, 2, 2, 1, 0,
       0, 1, 1, 1, 2, 0, 2, 1, 2, 0, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 0,
       1, 1, 2, 1, 2, 1, 1, 1, 2, 1, 1, 1, 0, 0, 1,

In [41]:
y_test

array([[0],
       [2],
       [1],
       ...,
       [2],
       [2],
       [2]])

In [80]:
from keras.utils import np_utils
NB_CLASSES =3
import numpy as np
y_train = np_utils.to_categorical(y_train, NB_CLASSES)
y_test = np_utils.to_categorical(y_test, NB_CLASSES)

In [81]:
y_train

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [44]:
y_train

array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.],
       ...,
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [77]:
#separate Train,test Data

def vfl_data(t,p):
    n=int(((100-p)/100)*t)
    print('Train Data:',t-(t-n),'Test Data:',t-n)
    dataTr=dataR[:n]
    dataTe=dataR[n:]
    
    x_train=dataTr[:,0:21]
    x2_train=x_train.reshape(n,7,3)
    x_train = x2_train[:, np.newaxis, :,:]
    y_train= dataTr[:,21]


    x1_test=dataTe[:,0:21]
    x2_test=x1_test.reshape(t-n,7,3)
    x_test = x2_test[:, np.newaxis, :,:]
    y_test= dataTe[:,21]
    return (x_train, y_train), (x_test, y_test)

(x_train, y_train), (x_test, y_test)=vfl_data(t,10)

Train Data: 503 Test Data: 56


ValueError: cannot reshape array of size 267813 into shape (56,7,3)

In [54]:
x_train

array([[[[ 2, 11,  2],
         [ 0,  2,  1],
         [ 0,  0,  2],
         ...,
         [11,  0,  0],
         [ 0,  1,  2],
         [ 3, -1,  0]]],


       [[[15, 12,  4],
         [ 0,  2,  1],
         [ 0,  0,  3],
         ...,
         [ 1,  0,  1],
         [ 0,  0,  3],
         [ 1,  2,  3]]],


       [[[13,  7,  7],
         [ 0,  2,  0],
         [ 1,  0,  2],
         ...,
         [10,  0,  0],
         [ 1,  0,  0],
         [ 0,  0,  1]]],


       ...,


       [[[13,  6, 12],
         [ 1,  9,  2],
         [ 2,  4, 10],
         ...,
         [ 4,  1,  4],
         [ 2,  2, 14],
         [ 7,  7, 14]]],


       [[[ 8,  2,  4],
         [ 1, 10,  4],
         [ 3,  2, 12],
         ...,
         [ 1, -1,  6],
         [ 2,  1, 13],
         [ 5,  8, 20]]],


       [[[ 6, 11,  5],
         [ 1, 10,  4],
         [ 2,  3, 15],
         ...,
         [ 7, -1,  3],
         [ 4,  2, 15],
         [13,  2, 13]]]])

In [55]:
x_test

array([[[[ 3, 13,  8],
         [ 1, 10,  3],
         [ 3,  3, 13],
         ...,
         [12,  0,  3],
         [ 2,  4, 13],
         [16, -3, 11]]],


       [[[15,  7, 10],
         [ 1, 10,  3],
         [ 3,  3, 12],
         ...,
         [ 3, -1,  4],
         [ 4,  1, 10],
         [ 4,  6, 16]]],


       [[[14,  4, 13],
         [ 0, 10,  2],
         [ 3,  4,  7],
         ...,
         [ 6, -1,  3],
         [ 4,  2, 13],
         [10,  3, 13]]],


       ...,


       [[[15,  4, 14],
         [ 1, 30,  8],
         [ 3, 18, 38],
         ...,
         [ 8, -1, 12],
         [ 4, 13, 43],
         [38,  5, 40]]],


       [[[13,  1, 15],
         [ 0, 30,  7],
         [ 5, 17, 21],
         ...,
         [ 2,  0, 16],
         [ 8,  5, 60],
         [33, 27, 56]]],


       [[[12,  7, 16],
         [ 0, 30,  7],
         [ 4, 18, 19],
         ...,
         [ 4,  0, 17],
         [ 5,  7, 43],
         [25, 18, 56]]]])

In [56]:
y_train

array([2, 2, 1, ..., 1, 1, 1])

In [57]:
y_test

array([1, 1, 2, ..., 0, 2, 2])

In [75]:

NB_CLASSES = 3 # number of outputs = number of digits///depend on what to predict


(x_train, y_train), (x_test, y_test)=vfl_data(t,10)

# consider them as float and normalize
X_train= (x_train.astype('float32'))/15
X_test= (x_test.astype('float32'))/15

print(X_train.shape[0], 'train samples')
print(X_test.shape[0], 'test samples')

X_train, X_test, y_train, y_test

y_train = np_utils.to_categorical(y_train, NB_CLASSES)
y_test = np_utils.to_categorical(y_test, NB_CLASSES)

Train Data: 503 Test Data: 56
503 train samples
12753 test samples


In [59]:
y_train

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       ...,
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.]], dtype=float32)

In [60]:
x_train

array([[[[ 2, 11,  2],
         [ 0,  2,  1],
         [ 0,  0,  2],
         ...,
         [11,  0,  0],
         [ 0,  1,  2],
         [ 3, -1,  0]]],


       [[[15, 12,  4],
         [ 0,  2,  1],
         [ 0,  0,  3],
         ...,
         [ 1,  0,  1],
         [ 0,  0,  3],
         [ 1,  2,  3]]],


       [[[13,  7,  7],
         [ 0,  2,  0],
         [ 1,  0,  2],
         ...,
         [10,  0,  0],
         [ 1,  0,  0],
         [ 0,  0,  1]]],


       ...,


       [[[13,  6, 12],
         [ 1,  9,  2],
         [ 2,  4, 10],
         ...,
         [ 4,  1,  4],
         [ 2,  2, 14],
         [ 7,  7, 14]]],


       [[[ 8,  2,  4],
         [ 1, 10,  4],
         [ 3,  2, 12],
         ...,
         [ 1, -1,  6],
         [ 2,  1, 13],
         [ 5,  8, 20]]],


       [[[ 6, 11,  5],
         [ 1, 10,  4],
         [ 2,  3, 15],
         ...,
         [ 7, -1,  3],
         [ 4,  2, 15],
         [13,  2, 13]]]])

In [76]:
(x_train, y_train), (x_test, y_test)=vfl_data(t,10)

Train Data: 503 Test Data: 56


In [82]:
# Import AI MODULES & FRAMEWORKS
from __future__ import division, print_function
from keras import backend as K
from keras.callbacks import ModelCheckpoint 
from keras.models import Sequential
from keras.layers.convolutional import Conv2D
#from keras.layers.convolutional import MaxPooling2D,AveragePooling2D
from keras.layers.pooling import AveragePooling2D,GlobalAveragePooling2D,MaxPooling2D,GlobalMaxPooling2D
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dense, Dropout 
#from keras_contrib
#from keras_contrib.layers.core import CosineDense
from keras.layers.advanced_activations import LeakyReLU
from keras.datasets import mnist
from keras.utils import np_utils
from keras.optimizers import SGD, RMSprop, Adam
from keras.layers import LSTM
from keras.layers.normalization import BatchNormalization
import numpy as np
import pylab as plt
import numpy as np
import matplotlib.pyplot as plt
import os 

from keras.initializers import TruncatedNormal

In [83]:
# #t= 559
# def vfl_data(t,p):
#     n=int(((100-p)/100)*t)
#     print('Train Data:',t-(t-n),'Test Data:',t-n)
#     dataTr=dataR[:n]
#     dataTe=dataR[n:]
    
#     x_train=dataTr[:,0:21]
#     x2_train=x_train.reshape(n,7,3)
#     #x_train = x2_train[:, np.newaxis, :,:]
#     y_train= dataTr[:,21]


#     x1_test=dataTe[:,0:21]
#     #x2_test=x1_test.reshape(t-n,7,3)
#    # x_test = x2_test[:, np.newaxis, :,:]
#     x_test = x1_test
#     y_test= dataTe[:,21]
    
#     return (x_train, y_train), (x_test, y_test)
# (x_train, y_train), (x_test, y_test)=vfl_data(t,10)

# from __future__ import print_function
# import numpy as np
# from keras.datasets import mnist
# from keras.models import Sequential
# from keras.layers.core import Dense, Dropout, Activation
# from keras.optimizers import SGD,Adam
# from keras.utils import np_utils
# import numpy as np
# import pylab as plt
# import numpy as np
# import matplotlib.pyplot as plt
# import os 



#np.random.seed(1671) # for reproducibility
# network and training
NB_EPOCH = 1
BATCH_SIZE = 35
VERBOSE = 1
NB_CLASSES = 3 # number of outputs = number of digits
OPTIMIZER =Adam() #SGD() # optimizer, explained later in this chapter
N_HIDDEN = 250
N_HIDDEN1 =600
#INITIAL_EPOCH = 0
VALIDATION_SPLIT=0.2 # how much TRAIN is reserved for VALIDATION
DROPOUT = 0.05
# data: shuffled and split between train and test sets
#(X_train, y_train), (X_test, y_test) = mnist.load_data()
(x_train, y_train), (x_test, y_test)=vfl_data(t,10)
#X_train is 60000 rows of 28x28 values --> reshaped in 60000 x 784
RESHAPED = 21
#
X_train = x_train.reshape(x_train.shape[0], RESHAPED)
X_test = x_test.reshape(x_test.shape[0], RESHAPED)
X_train = x_train.astype('float32')
X_test = x_test.astype('float32')
# normalize
X_train /= 5
X_test /= 5


# convert class vectors to binary class matrices..
Y_train = np_utils.to_categorical(y_train, NB_CLASSES)
Y_test = np_utils.to_categorical(y_test, NB_CLASSES)





# M_HIDDEN hidden layers 10 outputs
model = Sequential()
model.add(Dense(N_HIDDEN, input_shape=(RESHAPED,)))
model.add(Activation('relu'))
model.add(Dropout(DROPOUT))
model.add(Dense(N_HIDDEN1))
model.add(Activation('relu'))
model.add(Dropout(DROPOUT))
model.add(Dense(NB_CLASSES))
model.add(Activation('softmax'))
model.summary()



# Loss Train
model.compile(loss='categorical_crossentropy',optimizer=OPTIMIZER,metrics=['accuracy'])
history = model.fit(X_train, Y_train,batch_size=BATCH_SIZE, epochs=NB_EPOCH,verbose=VERBOSE,
                    validation_split=VALIDATION_SPLIT)
# Test

score = model.evaluate(X_test, Y_test, verbose=VERBOSE)
print("Test score:", score[0])
print('Test accuracy:', score[1])
def vfl_data(t,p):
    n=int(((100-p)/100)*t)
    print('Train Data:',t-(t-n),'Test Data:',t-n)
    dataTr=dataR[:n]
    dataTe=dataR[n:]
    
    x_train=dataTr[:,0:21]
    x2_train=x_train.reshape(n,7,3)
    #x_train = x2_train[:, np.newaxis, :,:]
    y_train= dataTr[:,21]


    x1_test=dataTe[:,0:21]
    #x2_test=x1_test.reshape(t-n,7,3)
   # x_test = x2_test[:, np.newaxis, :,:]
    x_test = x1_test
    y_test= dataTe[:,21]
    
    return (x_train, y_train), (x_test, y_test)
(x_train, y_train), (x_test, y_test)=vfl_data(t,10)

# from __future__ import print_function
# import numpy as np
# from keras.datasets import mnist
# from keras.models import Sequential
# from keras.layers.core import Dense, Dropout, Activation
# from keras.optimizers import SGD,Adam
# from keras.utils import np_utils
# import numpy as np
# import pylab as plt
# import numpy as np
# import matplotlib.pyplot as plt
# import os 



#np.random.seed(1671) # for reproducibility
# network and training
NB_EPOCH = 20
BATCH_SIZE = 35
VERBOSE = 1
NB_CLASSES = 3 # number of outputs = number of digits
OPTIMIZER =Adam() #SGD() # optimizer, explained later in this chapter
N_HIDDEN = 250
N_HIDDEN1 =600
#INITIAL_EPOCH = 0
VALIDATION_SPLIT=0.2 # how much TRAIN is reserved for VALIDATION
DROPOUT = 0.05
# data: shuffled and split between train and test sets
#(X_train, y_train), (X_test, y_test) = mnist.load_data()
(x_train, y_train), (x_test, y_test)=vfl_data(t,10)
#X_train is 60000 rows of 28x28 values --> reshaped in 60000 x 784
RESHAPED = 21
#
X_train = x_train.reshape(x_train.shape[0], RESHAPED)
X_test = x_test.reshape(x_test.shape[0], RESHAPED)
X_train = x_train.astype('float32')
X_test = x_test.astype('float32')
# normalize
X_train /= 5
X_test /= 5


# convert class vectors to binary class matrices..
Y_train = np_utils.to_categorical(y_train, NB_CLASSES)
Y_test = np_utils.to_categorical(y_test, NB_CLASSES)





# M_HIDDEN hidden layers 10 outputs
model = Sequential()
model.add(Dense(N_HIDDEN, input_shape=(RESHAPED,)))
model.add(Activation('relu'))
model.add(Dropout(DROPOUT))
model.add(Dense(N_HIDDEN1))
model.add(Activation('relu'))
model.add(Dropout(DROPOUT))
model.add(Dense(NB_CLASSES))
model.add(Activation('softmax'))
model.summary()



# Loss Train
model.compile(loss='categorical_crossentropy',optimizer=OPTIMIZER,metrics=['accuracy'])
history = model.fit(X_train, Y_train,batch_size=BATCH_SIZE, epochs=NB_EPOCH,verbose=VERBOSE,
                    validation_split=VALIDATION_SPLIT)
# Test

score = model.evaluate(X_test, Y_test, verbose=VERBOSE)
print("Test score:", score[0])
print('Test accuracy:', score[1])

Train Data: 503 Test Data: 56


ValueError: cannot reshape array of size 267813 into shape (56,7,3)

In [70]:
#SETTINGS##

#MODEL_DIR = "/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/" #over2.5
MODEL_DIR = "/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/hxa/"
MODEL_DIR2 = "/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/MOD/"

BATCH_SIZE = 20
VERBOSE = 1
OPTIMIZER = Adam()
VALIDATION_SPLIT=0.15
ROWS,COLS = 7, 3 # input image dimensions
INPUT_SHAPE = (1, ROWS, COLS)

count = 0
NB_EPOCH = 20
INITIAL_EPOCH = 0


In [84]:
#for step in range(1):

model = gNet.build(input_shape=INPUT_SHAPE, classes=NB_CLASSES)

#model.compile(loss="binary_crossentropy", optimizer=OPTIMIZER,metrics=["accuracy"])

model.compile(loss='categorical_crossentropy', optimizer=OPTIMIZER, metrics=['accuracy'])

# save best model 
checkpoint = ModelCheckpoint( filepath=os.path.join(MODEL_DIR, "model-{epoch:02d}.h5"),save_best_only=True) 

history = model.fit(X_train, y_train,batch_size=BATCH_SIZE, epochs=NB_EPOCH,initial_epoch = INITIAL_EPOCH,verbose=VERBOSE,validation_split=VALIDATION_SPLIT,callbacks=[checkpoint])
score = model.evaluate(X_test, y_test, verbose=VERBOSE)

# save best model with
checkpoint = ModelCheckpoint( filepath=os.path.join(MODEL_DIR2, "model-{epoch:02d}.h5"),save_best_only=True)
#sleep(2)
print("Test score:", score[0])
print('Test accuracy:', score[1])
#print('Test accuracy percentage:', round(score[1]*100,3),'%')
#model.save('g8FT_model.h5')

NameError: name 'gNet' is not defined

In [ ]:
# list all data in history
print(history.history.keys())
# summarize history for accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [ ]:
# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [ ]:
from keras.models import load_model

model.save("/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/USE/vfl_model.h5")  # creates a HDF5 file 'my_model.h5'
#del model  # deletes the existing model



In [ ]:
# Import AI MODULES & FRAMEWORKS
from __future__ import division, print_function
from keras import backend as K
from keras.callbacks import ModelCheckpoint 
from keras.models import Sequential
from keras.layers.convolutional import Conv2D
#from keras.layers.convolutional import MaxPooling2D,AveragePooling2D
from keras.layers.pooling import AveragePooling2D,GlobalAveragePooling2D,MaxPooling2D,GlobalMaxPooling2D
from keras.layers.core import Activation
from keras.layers.core import Flatten
from keras.layers.core import Dense, Dropout 
#from keras_contrib
#from keras_contrib.layers.core import CosineDense
from keras.layers.advanced_activations import LeakyReLU
from keras.datasets import mnist
from keras.utils import np_utils
from keras.optimizers import SGD, RMSprop, Adam
from keras.layers import LSTM
from keras.layers.normalization import BatchNormalization
import numpy as np
import pylab as plt
import numpy as np
import matplotlib.pyplot as plt
import os 

from keras.initializers import TruncatedNormal

In [ ]:
# returns a compiled model
# identical to the previous one
model = load_model("/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/USE/vfl_model.h5")

In [ ]:
#SETTINGS##

#MODEL_DIR = "/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/" #over2.5
MODEL_DIR = "/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/hxa/"
MODEL_DIR2 = "/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/MOD/"

BATCH_SIZE = 5
VERBOSE = 1
OPTIMIZER = Adam()
VALIDATION_SPLIT=0.15
ROWS,COLS = 7, 3 # input image dimensions
INPUT_SHAPE = (1, ROWS, COLS)

count = 0
NB_EPOCH = 30
INITIAL_EPOCH = 0


In [ ]:
checkpoint = ModelCheckpoint( filepath=os.path.join(MODEL_DIR, "model-{epoch:02d}.h5"),save_best_only=True) 
history = model.fit(X_train, y_train,batch_size=BATCH_SIZE, epochs=NB_EPOCH,initial_epoch = INITIAL_EPOCH,verbose=VERBOSE,validation_split=VALIDATION_SPLIT,callbacks=[checkpoint])
score = model.evaluate(X_test, y_test, verbose=VERBOSE)

# save best model with
checkpoint = ModelCheckpoint( filepath=os.path.join(MODEL_DIR2, "model-{epoch:02d}.h5"),save_best_only=True)
#sleep(2)
print("Test score:", score[0])
print('Test accuracy:', score[1])
#print('Test accuracy percentage:', round(score[1]*100,3),'%')
#model.save('g8FT_model.h5')

In [ ]:
#model.save("/home/gibeon/Desktop/MY/fvldata/STORAGE/Models/USE/vfl{}_model.h5".format(score[1]))

In [ ]:
# list all data in history
print(history.history.keys())
# summarize history for accuracy
plt.plot(history.history['acc'])
plt.plot(history.history['val_acc'])
plt.title('model accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()

In [ ]:
# summarize history for loss
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')
plt.show()